### ISSUE TITLE
Does KRANK work with long reads?

### ISSUE THREAD

**Issue by spoonbender76** [bo1929/KRANK#1]
Hi,

I recently discovered CONSULT, CONSULT-II, and KRANK. I'm curious if these tools are compatible with long-read genomic sequencing reads (PacBio HiFi for my case), as the test data I've seen are all 150bp short reads.

Additionally, for contamination removal from genomic sequencing reads, would you recommend CONSULT-II or KRANK over CONSULT? Are there any noticeable improvements in accuracy or speed?

Thanks in advance for your insights!

**Comment by bo1929** [comment]
Hi,

- We haven't done any benchmarking with long reads, so I don't really have a strong insight. I believe it is worth testing. I cannot think of any particular reason for it to not perform reasonably if parameters are tuned accordingly. Some default parameter values are set for short reads (e.g., `--tvote-threshold` should probably be much higher). But of course, I hesitate to recommend it for long reads without some benchmarking, which I hope to do soon.

- I strongly recommend KRANK over CONSULT and CONSULT-II because I believe it is a better piece of software, and easier to use. Performance-wise, there wouldn't be a noticeable difference for contamination removal, but resource use (both memory and time) will be lower with KRANK.

I'd be happy to help if you have any issues or further questions.

Good luck!
